FROM node:20-slim AS builder

# Install Java (Required for Shadow-CLJS)
RUN apt-get update && apt-get install -y default-jre && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy package.json first
COPY package.json package-lock.json ./
RUN npm install

# Copy project files
COPY . .

# Run Havok Copy Script & Build Release
RUN chmod +x sh/copy_havok.sh && ./sh/copy_havok.sh
RUN npx shadow-cljs release app

# Serve Stage
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/resources/public /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
